name: Test build
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Up all services
        run: docker-compose up
